// <auto-generated />
namespace Last_Dance_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddInstructorSessionReviews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInstructorSessionReviews));
        
        string IMigrationMetadata.Id
        {
            get { return "202608292154096_AddInstructorSessionReviews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
