// <auto-generated />
namespace Last_Dance_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddInstructorFeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInstructorFeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "202608312045266_AddInstructorFeedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
